### ISSUE TITLE
runExample() Error

### ISSUE THREAD

**Issue by amandamasonsingh** [jasdumas/shinyLP#10]
I keep getting this error when I try the runExample() function (using the shinyLP package 1.1.1 from CRAN):

`shinyLP::runExample()`

> Listening on http://IP
> Warning: Error in list_group: unused argument (list_item("User Updates", badge_value = 24))
> Stack trace (innermost first):
>     55: list_group
>     54: tag
>     53: tags$div
>     52: div
>     51: tabPanel
>     50: navbarPage
>     49: tag
>     48: tags$div
>     47: div
>     46: tagList
>     45: attachDependencies
>     44: bootstrapPage
>     43: fluidPage
>     42: shinyUI
>      2: shiny::runApp
>      1: shinyLP::runExample
> Error : unused argument (list_item("User Updates", badge_value = 24))
> Warning: Error in list_group: unused argument (list_item("User Updates", badge_value = 24))
> Stack trace (innermost first):
>     55: list_group
>     54: tag
>     53: tags$div
>     52: div
>     51: tabPanel
>     50: navbarPage
>     49: tag
>     48: tags$div
>     47: div
>     46: tagList
>     45: attachDependencies
>     44: bootstrapPage
>     43: fluidPage
>     42: shinyUI
>      2: shiny::runApp
>      1: shinyLP::runExample
> Error : unused argument (list_item("User Updates", badge_value = 24))

What is the error here?  It looks like something might be broken in the runExample code?

I can get the shinyLP::runExample() function to work when I install the package from this GitHub repo and install the following dependency, though: `install.packages(c("httpuv"))`

**Comment by jasdumas** [comment]
:wave: yeah sorry about the error from the CRAN side. I updated the [GitHub version with the fix](https://github.com/jasdumas/shinyLP/issues/8) and will submit to CRAN soon! `httpuv` is not a dependency though.

Thanks for using shinyLP!

**Comment by jasdumas** [comment]
the fix is on cran now! https://cran.r-project.org/package=shinyLP

**Comment by amandamasonsingh** [comment]
So weird (the httpuv package not being a dependency)!

Thanks for pushing the fix!
