### ISSUE TITLE
Error on shinyLP::runExample()

### ISSUE THREAD

**Issue by abjeroen** [jasdumas/shinyLP#14]
Error on 
`shinyLP::runExample()`

Listening on http://127.0.0.1:6057
Warning: Error in file.path: cannot coerce type 'closure' to vector of type 'character'
  [No stack trace available]

R version 3.6.3 (2020-02-29)

**Comment by jdumas-fastly** [comment]
Hi! I'm not seeing the same error. 

I'm using R version 4.0.2 (2020-06-22) -- "Taking Off Again & Platform: x86_64-apple-darwin17.0 (64-bit) and the example app does run.
