### ISSUE TITLE
Use button_link of thumbnail_label to navigate to Tab of Shinydashboard

### ISSUE THREAD

**Issue by franciscopauloricardo** [jasdumas/shinyLP#15]
Good morning,

Is it possible to use the "button link" of the thumbnail_label to link to a shinydashboard tab? I would like to use the landing page of ShinyLP as a quick way for the user to navigate for the indented tab.

#Sidebar
sidebar <- dashboardSidebar(
  
  sidebarMenu(
    
    menuItem("Home", tabName = "Home")
    ,menuItem("About", tabName = "aboutTab")
    
    
  )#Fim de sidebarMenu
  
)#Fim de dashboardSidebar

body <- dashboardBody(
  
	tabItems(
    
    #Conteudo da Tab Home
    
    tabItem(tabName = "Home"
	
	,column(4, thumbnail_label(image = 'Rlogo.png', label = 'Spray Drying Search',
                                        content = 'Havana brown cornish rex bombay but bombay,
                                              but havana brown devonshire rex and devonshire rex.
                                              Tomcat egyptian mau. Cornish rex sphynx sphynx yet
                                              cougar and panther. Panther siberian. Lynx munchkin
                                              american shorthair. Norwegian forest. ',
                                        button_link = 'http://getbootstrap.com/', button_label = 'Click me')
	
	)#End of tab Home
	
	
	
	,tabItem(tabName = "aboutTab")#End of tab aboutTab
	
	)#End of tabItems
	
	)#End of dashboardBody

Kind regards,
Paulo

**Comment by jdumas-fastly** [comment]
Hi! I think you should be able to do that by specifying the link as:
```r 
button_link = 'https://YOUR_SHINY_SERVER_LOCATION/#shiny-tab-aboutTab'

```
