### ISSUE TITLE
How to make thumbnail_label a fixed size?

### ISSUE THREAD

**Issue by prcleary** [jasdumas/shinyLP#2]
Great package which I am using to link to several Shiny apps within a corporate network. 

Is it possible to give a fixed size to each thumbnail_label element? (as in height)

Thanks

**Comment by jasdumas** [comment]
Hi, thanks for using `shinyLP`! I believe the height is only really driven by the amount of text content. Do you have an example of what you are trying to achieve?

**Comment by prcleary** [comment]
Thanks - I think I worked it out. 

I added the following to `ui.r`:

```
      tags$style(HTML('
                      .thumbnail {
                      height: 400px;}')
```
