### ISSUE TITLE
support software citation import

### ISSUE THREAD

**Issue by katrinleinweber** [jasdumas/shinyLP#5]
Hello!

Landing pages for any kind of software project are one of the cornerstones of the [Software Citation Principles](https://peerj.com/articles/cs-86/). So, 1k thanks for helping to make them easier to generate :-)

I'd like to start a discussion here about whether & how shinyLP could support the citation workflow with features that expose relevant metadata to for example a [Zotero](https://www.zotero.org/) [translator](https://github.com/zotero/translators). For 1-click import into user's own reference library :-)

Cheers!

**Comment by jasdumas** [comment]
👋 I'm not even sure where to begin on this idea! If you have an example of how this could be potentially implemented that would be helpful for this discussion. From initial glance, this seems like a project fit for a separate R 📦as `shinyLP`s singular goal is to provide user-friendly bootstrap components for the UI section of shiny apps.

**Comment by katrinleinweber** [comment]
My apologies for this delay. I looked through the [Shiny lessons](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/) and found no defined way to include citation-relevant metadata (like in a package's `DESCRIPTION`). So, there might be nothing to go on, but OTOH, this is an opportunity to provide components that do encourage people to add citation-relevant metadata to their Shiny apps and landing pages.

See [Zotero's R-Packages.js](https://github.com/zotero/translators/blob/master/R-Packages.js#L92) for example. It extracts metadata from [CRAN pages](https://cran.r-project.org/web/packages/knitrBootstrap/index.html) based on CSS & HTML elements.

However, I don't see this as an immediately useful feature, but rather as an academic best-practice. For example: a collection of Shiny apps that are supplementary material to a research paper could be seen as a citable entity themselves, or the Shiny landing page could be used to the expose the citation metadata of the "parent" paper.
