### ISSUE TITLE
error runExample()

### ISSUE THREAD

**Issue by Rhoboot** [jasdumas/shinyLP#8]
Hello Jasmine:

I have tried to execute the example, but it gives me an error

`shinyLP :: runExample ()`

ERROR: unused argument (list_item("User Updates", badge_value = 24))

apparently the list_group function allows only one element

`list_group(list_item("Application Updates", badge_value = 27),list_item("User Updates", badge_value = 24))`

regards

**Comment by jasdumas** [comment]
Hi, try wrapping your list groups with a `div()` like this:

```r
list_group(div(list_item("Application Updates", badge_value = 27),list_item("User Updates", badge_value = 24)))
```

ahh sorry, thats my mistake for having development functions in my playground environment. 🤷‍♀️  I will push an update to GitHub soon.

**Comment by Rhoboot** [comment]
Excellent thank you very much
